package reedSolomonV2;

import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;

import javax.smartcardio.CardException;

public class Main {
	/**
	 * Implements the reversible degradation, with reed-solomon and nfc encoded: the
	 * absolute path of the file that has been encoded and degradeted redundancy:
	 * the error correction bytes generated by the encoder process hash: the
	 * absolute path of the file matching the hash generated by the card that
	 * encoded the file
	 * 
	 * @param args main to execute the code, has a self implementation for static
	 *             methods
	 * @throws NoSuchAlgorithmException default sha256 exception
	 * @throws IOException              if for any reason the data to be degradeted
	 *                                  it's unavailable in the disk
	 * @throws ReedSolomonException     exception to handle the error correction
	 *                                  code
	 * @throws CardException            pc card reader default exception, if for any
	 *                                  reason there is no card in the reader or if
	 *                                  the reader itself is unavailable
	 * @throws InterruptedException 
	 */

	public static void main(String[] args)
			throws NoSuchAlgorithmException, IOException, ReedSolomonException, CardException, InterruptedException {

		ReversibleDegradation degradation = new ReversibleDegradation();
		int degradationPercent = 5, m = 16;
		String absolutePath = "Z:\\The Art of Data Hiding with Reed-Solomon Error Correcting Codes.pdf";
		String encoded = "Z:\\The Art of Data Hiding with Reed-Solomon Error Correcting Codes_Encoded.pdf";
		String redundancy = "Z:\\The Art of Data Hiding with Reed-Solomon Error Correcting Codes_Redundancy.pdf";
		String hash = "Z:\\The Art of Data Hiding with Reed-Solomon Error Correcting Codes_Hash.pdf";
		SHA512 sha512 = new SHA512();
		NFCHandle nfc = new NFCHandle();
		byte[] uid = nfc.UID();
		//System.out.println(Arrays.toString(uid));
		byte[] sha5122 = sha512.sha512(uid);
		
		System.out.println(Arrays.toString(sha5122));
		System.out.println(sha5122.length);
		
		
		// Encoder
		//degradation.encoder(absolutePath, degradationPercent, m);

		// Decoder
		//degradation.decoder(absolutePath, encoded, redundancy, hash, degradationPercent, m);

	}

}
